Repository CarlosGLOZ/Tienda-Sintesis, pull requests merged in 2023-03, with the labels that each got.

#12 ajustes merge muga-dev
  resources/css/auth.css
  resources/css/auth.less
  resources/css/filters.css
  resources/css/filters.less
  resources/css/header.css
  resources/css/header.less
  resources/css/navbar.css
  resources/css/navbar.less
  resources/views/components/header.blade.php
  resources/views/components/navbar.blade.php
  resources/views/components/search_filters.blade.php
Labels: frontend

#13 auth responsive
  resources/css/auth.css
  resources/css/auth.less
Labels: frontend

#14 Hector
  app/Http/Controllers/AuthController.php
  public/correo.js
  resources/css/app.css
  resources/views/components/correo.blade.php
  vendor/composer/installed.php
Labels: frontend

#15 pago funcional
  app/Http/Controllers/ProductController.php
  composer.lock
  resources/views/cart/view.blade.php
  routes/web.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.php
Labels: backend

#17 Carlos
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/ProductController.php
  resources/css/afterPurchase.css
  resources/css/afterPurchase.less
  resources/css/app.css
  resources/css/app.less
  resources/css/cart.css
  resources/css/cart.less
  resources/views/cart.blade.php
  resources/views/cart/afterPurchase.blade.php
  resources/views/cart/view.blade.php
  routes/web.php
Labels: frontend

#19 Carlos
  app/Http/Controllers/ProductController.php
  resources/css/crud.css
  resources/css/crud.less
  resources/js/crud_productos.js
  resources/views/product/create.blade.php
  routes/web.php
Labels: backend, frontend
